---
- name: ensure dependencies are installed.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ elasticsearch_const[ansible_os_family]['dependencies'] }}"

- name: add elastic.co repo
  block:
    - name: add elastic.co gpg key
      ansible.builtin.apt_key:
        url: "{{ elasticsearch_const[ansible_os_family]['elastic_gpg'] }}"
        state: present

    - name: add elastic.co repo
      ansible.builtin.apt_repository:
        repo: "{{ elasticsearch_const[ansible_os_family]['elastic_repo'] }}"
        state: present
  when: elasticsearch.repo == "elastic"

- name: install elasticsearch
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ elasticsearch_const[ansible_os_family]['packages'] }}"

- name: force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true