---
- name: ensure dependencies are installed.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ elasticsearch_const[ansible_os_family]['dependencies'] }}"

- name: add elasticsearch repo for redhat
  block:
    - name: import elasticsearch gpg key
      ansible.builtin.rpm_key:
        key: "{{ elasticsearch_const[ansible_os_family]['elastic_gpg'] }}"
        state: present

    - name: add elasticsearch repository
      ansible.builtin.yum_repository:
        name: "elasticsearch"
        description: "Elasticsearch repository"
        baseurl: "{{ elasticsearch_const[ansible_os_family]['elastic_repo'] }}"
        gpgcheck: true
        enabled: true
        module_hotfixes: true
  when: elasticsearch.repo == "elastic"

- name: install elasticsearch
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ elasticsearch_const[ansible_os_family]['packages'] }}"