---
- name: configure elasticsearch_yml
  ansible.builtin.template:
    src: "{{ elasticsearch_yml.src }}"
    dest: "/etc/elasticsearch/{{ elasticsearch_yml.file }}"
    owner: root
    group: elasticsearch
    mode: 0660
    backup: "{{ elasticsearch_yml.backup }}"
  notify: restart elasticsearch
  when: elasticsearch_yml.enabled

- name: configure elasticsearch_jvm_options
  ansible.builtin.template:
    src: "{{ elasticsearch_jvm_options.src }}"
    dest: "/etc/elasticsearch/{{ elasticsearch_jvm_options.file }}"
    owner: root
    group: elasticsearch
    mode: 0660
    backup: "{{ elasticsearch_jvm_options.backup }}"
  notify: restart elasticsearch
  when: elasticsearch_jvm_options.enabled