---
- name: merge dictionaries
  block:
    - include_vars:
        file: ../../darexsu.elasticsearch/defaults/main.yml
        name: elasticsearch_default_vars

    - name: merge default and new dictionaries
      set_fact:
        "{{ item.key }}": "{{ elasticsearch_default_vars[item.key] | combine(merge[item.key], recursive=True)}}"
      when: elasticsearch_default_vars[item.key] is defined
      with_dict: "{{ merge }}"

    - name: combine defaults vars with merge dictionary
      set_fact:
        merge: "{{ elasticsearch_default_vars | combine(merge, recursive=True)}}"
  when: merge is defined

- name: elasticsearch role is disabled
  meta: end_play
  when: not elasticsearch.enabled

- name: "-> 01_Elasticsearch_install_{{ ansible_os_family }}.yml"
  include_tasks: "./tasks/01_Elasticsearch_install_{{ ansible_os_family }}.yml"
  when: elasticsearch_install.enabled

- name: gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: "-> 02_Elasticsearch_config.yml"
  include_tasks: "./tasks/02_Elasticsearch_config.yml"
  when: ("elasticsearch") in ansible_facts.packages

- name: "ensure elasticsearch is {{ elasticsearch['service']['state'] }}"
  ansible.builtin.service:
    name: elasticsearch
    state: "{{ elasticsearch['service']['state'] }}"
    enabled: "{{ elasticsearch['service']['enabled'] }}"
  when: ("elasticsearch") in ansible_facts.packages