---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Unnessessary command
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
      when: lookup('env', 'ANSIBLE_COMMAND') | length > 0

  vars:
    merge:
      # ElasticSearch
      elasticsearch:
        enabled: true
        version: "8.x"
        repo: "elastic"
        service:
          enabled: true
          state: "started"
      # ElasticSearch -> install
      elasticsearch_install:
        enabled: true
        packages: ["elasticsearch"]
      # ElasticSearch -> config -> elasticsearch.yml
      elasticsearch_yml:
        enabled: true
        file: "elasticsearch.yml"
        src: "elasticsearch_yml.j2"
        backup: false
        data: |
          path.data: /var/lib/elasticsearch
          path.logs: /var/log/elasticsearch
          xpack.security.enabled: false
          xpack.security.enrollment.enabled: true
          xpack.security.http.ssl:
            enabled: true
            keystore.path: certs/http.p12
          xpack.security.transport.ssl:
            enabled: true
            verification_mode: certificate
            keystore.path: certs/transport.p12
            truststore.path: certs/transport.p12
          http.host: [_local_, _site_]
      # ElasticSearch -> config -> elasticsearch.yml
      elasticsearch_jvm_options:
        enabled: true
        file: "jvm.options"
        src: "jvm_options.j2"
        backup: false
        data: |
          8-13:-XX:+UseConcMarkSweepGC
          8-13:-XX:CMSInitiatingOccupancyFraction=75
          8-13:-XX:+UseCMSInitiatingOccupancyOnly
          14-:-XX:+UseG1GC
          -Djava.io.tmpdir=${ES_TMPDIR}
          -XX:+HeapDumpOnOutOfMemoryError
          9-:-XX:+ExitOnOutOfMemoryError
          -XX:HeapDumpPath=/var/lib/elasticsearch
          -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log
          -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m

  tasks:
    - name: role darexsu elasticsearch
      include_role:
        name: darexsu.elasticsearch